2016-06-26 14:14:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS SPR_NSI_TYPE (ID identity not null primary key, NSI_TYPE varchar(20) not null;COMMENT ON TABLE ""PUBLIC"".SPR_NSI_TYPE IS '{Хранит типы справочников ГИС ЖКХ. НСИ или НСИРАО;COMMENT ON COLUMN SPR_NSI_TYPE.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI_TYPE.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.[*]';"
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS SPR_NSI_TYPE (ID identity not null primary key, NSI_TYPE varchar(20) not null;COMMENT ON TABLE ""PUBLIC"".SPR_NSI_TYPE IS '{Хранит типы справочников ГИС ЖКХ. НСИ или НСИРАО;COMMENT ON COLUMN SPR_NSI_TYPE.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI_TYPE.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.[*]';" [42000-190]
2016-06-26 14:21:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS SPR_NSI_TYPE (ID IDENTITY NOT NULL PRIMARY KEY, NSI_TYPE VARCHAR(20) NOT NULL;[*]COMMENT ON TABLE ""PUBLIC"".SPR_NSI_TYPE IS 'Хранит типы справочников ГИС ЖКХ. НСИ или НСИРАО.'; COMMENT ON COLUMN SPR_NSI_TYPE.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI_TYPE.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.'; "; ожидалось "AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS SPR_NSI_TYPE (ID IDENTITY NOT NULL PRIMARY KEY, NSI_TYPE VARCHAR(20) NOT NULL;[*]COMMENT ON TABLE ""PUBLIC"".SPR_NSI_TYPE IS 'Хранит типы справочников ГИС ЖКХ. НСИ или НСИРАО.'; COMMENT ON COLUMN SPR_NSI_TYPE.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI_TYPE.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.'; "; expected "AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE IF NOT EXISTS SPR_NSI_TYPE (ID identity not null primary key, NSI_TYPE varchar(20) not null;COMMENT ON TABLE "PUBLIC".SPR_NSI_TYPE IS 'Хранит типы справочников ГИС ЖКХ. НСИ или НСИРАО.'; COMMENT ON COLUMN SPR_NSI_TYPE.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI_TYPE.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.'; [42001-190]
2016-06-26 14:26:57 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-26 14:27:08 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setRequest(SaveToBaseMessages.java:35)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:102)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportOrgRegistry.callExportOrgRegistry(ExportOrgRegistry.java:66)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:62)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-26 14:27:08 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setResult(SaveToBaseMessages.java:69)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:104)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportOrgRegistry.callExportOrgRegistry(ExportOrgRegistry.java:66)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:62)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-26 14:27:09 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setRequest(SaveToBaseMessages.java:35)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:102)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportDataProvider.callExportDataProvide(ExportDataProvider.java:56)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:66)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-26 14:27:09 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setResult(SaveToBaseMessages.java:69)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:104)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportDataProvider.callExportDataProvide(ExportDataProvider.java:56)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:66)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-26 14:27:09 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.SaveToBaseOrganization.setOrganization(SaveToBaseOrganization.java:34)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:71)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-26 14:27:09 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.UsersDAO.<init>(UsersDAO.java:24)
	at ru.progmatik.java.web.accounts.ProfileSingleton.<init>(ProfileSingleton.java:27)
	at ru.progmatik.java.web.accounts.ProfileSingleton.instance(ProfileSingleton.java:46)
	at ru.progmatik.java.web.servlets.web.LoginClient.<init>(LoginClient.java:45)
	at ru.progmatik.java.web.servlets.web.LoginClient.<init>(LoginClient.java:49)
	at ru.progmatik.java.pregis.Main.main(Main.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-26 14:28:11 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-26 14:28:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS NSI_FOR_DOWNLOAD (ID identity not null primary key, CODE varchar(20) not null, WORD_FOR_EXTRACT varchar(255) not null, NSI_TYPE varchar(20) not null); COMMENT ON TABLE ""PUBLIC"".NSI_FOR_DOWNLOAD IS '{Хранит коды справочников и название элементов для извлечения;COMMENT ON COLUMN NSI_FOR_DOWNLOAD.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN NSI_FOR_DOWNLOAD.CODE IS 'Код справочника, который необходимо загрузить.'; COMMENT ON COLUMN NSI_FOR_DOWNLOAD.WORD_FOR_EXTRACT IS 'Для извлечения нужного элемента из справочника, используется ключевое слово.';COMMENT ON COLUMN NSI_FOR_DOWNLOAD.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.[*]'; ALTER TABLE ""PUBLIC"".NSI_FOR_DOWNLOAD ADD FOREIGN KEY (NSI_TYPE) REFERENCES ""PUBLIC"".NSI_TYPE(ID);"
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS NSI_FOR_DOWNLOAD (ID identity not null primary key, CODE varchar(20) not null, WORD_FOR_EXTRACT varchar(255) not null, NSI_TYPE varchar(20) not null); COMMENT ON TABLE ""PUBLIC"".NSI_FOR_DOWNLOAD IS '{Хранит коды справочников и название элементов для извлечения;COMMENT ON COLUMN NSI_FOR_DOWNLOAD.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN NSI_FOR_DOWNLOAD.CODE IS 'Код справочника, который необходимо загрузить.'; COMMENT ON COLUMN NSI_FOR_DOWNLOAD.WORD_FOR_EXTRACT IS 'Для извлечения нужного элемента из справочника, используется ключевое слово.';COMMENT ON COLUMN NSI_FOR_DOWNLOAD.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.[*]'; ALTER TABLE ""PUBLIC"".NSI_FOR_DOWNLOAD ADD FOREIGN KEY (NSI_TYPE) REFERENCES ""PUBLIC"".NSI_TYPE(ID);" [42000-190]
2016-06-26 14:30:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "NSI_TYPE" не найдена
Table "NSI_TYPE" not found; SQL statement:
CREATE TABLE IF NOT EXISTS NSI_FOR_DOWNLOAD (ID identity not null primary key, CODE varchar(20) not null, WORD_FOR_EXTRACT varchar(255) not null, NSI_TYPE varchar(20) not null); COMMENT ON TABLE "PUBLIC".NSI_FOR_DOWNLOAD IS 'Хранит коды справочников и название элементов для извлечения.';COMMENT ON COLUMN NSI_FOR_DOWNLOAD.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN NSI_FOR_DOWNLOAD.CODE IS 'Код справочника, который необходимо загрузить.'; COMMENT ON COLUMN NSI_FOR_DOWNLOAD.WORD_FOR_EXTRACT IS 'Для извлечения нужного элемента из справочника, используется ключевое слово.';COMMENT ON COLUMN NSI_FOR_DOWNLOAD.NSI_TYPE IS 'Тип справочника НСИ или НСИРАО.'; ALTER TABLE "PUBLIC".NSI_FOR_DOWNLOAD ADD FOREIGN KEY (NSI_TYPE) REFERENCES "PUBLIC".NSI_TYPE(ID); [42102-190]
2016-06-26 14:36:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS SPR_NSI (ID identity not null primary key, NAME varchar(255) not null, CODE varchar(20) not null, GUID varchar(40), GROUP_NAME varchar(255), CODE_PARENT varchar(20)); COMMENT ON TABLE ""PUBLIC"".SPR_NSI IS 'Справочник НСИ ГИС ЖКХ.COMMENT ON COLUMN SPR_NSI.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI.NAME IS 'Наименование поля элемента справочника.'; COMMENT ON COLUMN SPR_NSI.CODE IS 'Код элемента справочника, уникальный в пределах справочника.'; COMMENT ON COLUMN SPR_NSI.GUID IS 'Глобально-уникальный идентификатор элемента справочника ГИС ЖКХ.'; COMMENT ON COLUMN SPR_NSI.GROUP_NAME IS 'Название группы, если такая имеется, которая объединяет элементы справочника.'; COMMENT ON COLUMN SPR_NSI.CODE_PARENT IS 'Код родительского справочника.[*]';"
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS SPR_NSI (ID identity not null primary key, NAME varchar(255) not null, CODE varchar(20) not null, GUID varchar(40), GROUP_NAME varchar(255), CODE_PARENT varchar(20)); COMMENT ON TABLE ""PUBLIC"".SPR_NSI IS 'Справочник НСИ ГИС ЖКХ.COMMENT ON COLUMN SPR_NSI.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI.NAME IS 'Наименование поля элемента справочника.'; COMMENT ON COLUMN SPR_NSI.CODE IS 'Код элемента справочника, уникальный в пределах справочника.'; COMMENT ON COLUMN SPR_NSI.GUID IS 'Глобально-уникальный идентификатор элемента справочника ГИС ЖКХ.'; COMMENT ON COLUMN SPR_NSI.GROUP_NAME IS 'Название группы, если такая имеется, которая объединяет элементы справочника.'; COMMENT ON COLUMN SPR_NSI.CODE_PARENT IS 'Код родительского справочника.[*]';"; SQL statement:
CREATE TABLE IF NOT EXISTS SPR_NSI (ID identity not null primary key, NAME varchar(255) not null, CODE varchar(20) not null, GUID varchar(40), GROUP_NAME varchar(255), CODE_PARENT varchar(20)); COMMENT ON TABLE "PUBLIC".SPR_NSI IS 'Справочник НСИ ГИС ЖКХ.COMMENT ON COLUMN SPR_NSI.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI.NAME IS 'Наименование поля элемента справочника.'; COMMENT ON COLUMN SPR_NSI.CODE IS 'Код элемента справочника, уникальный в пределах справочника.'; COMMENT ON COLUMN SPR_NSI.GUID IS 'Глобально-уникальный идентификатор элемента справочника ГИС ЖКХ.'; COMMENT ON COLUMN SPR_NSI.GROUP_NAME IS 'Название группы, если такая имеется, которая объединяет элементы справочника.'; COMMENT ON COLUMN SPR_NSI.CODE_PARENT IS 'Код родительского справочника.'; [42000-190]
2016-06-26 14:39:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL " COMMENT ON TABLE ""PUBLIC"".SPR_NSI IS 'Справочник НСИ ГИС ЖКХ.'COMMENT[*] ON COLUMN SPR_NSI.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI.NAME IS 'Наименование поля элемента справочника.'; COMMENT ON COLUMN SPR_NSI.CODE IS 'Код элемента справочника, уникальный в пределах справочника.'; COMMENT ON COLUMN SPR_NSI.GUID IS 'Глобально-уникальный идентификатор элемента справочника ГИС ЖКХ.'; COMMENT ON COLUMN SPR_NSI.GROUP_NAME IS 'Название группы, если такая имеется, которая объединяет элементы справочника.'; COMMENT ON COLUMN SPR_NSI.CODE_PARENT IS 'Код родительского справочника.';"
Syntax error in SQL statement " COMMENT ON TABLE ""PUBLIC"".SPR_NSI IS 'Справочник НСИ ГИС ЖКХ.'COMMENT[*] ON COLUMN SPR_NSI.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI.NAME IS 'Наименование поля элемента справочника.'; COMMENT ON COLUMN SPR_NSI.CODE IS 'Код элемента справочника, уникальный в пределах справочника.'; COMMENT ON COLUMN SPR_NSI.GUID IS 'Глобально-уникальный идентификатор элемента справочника ГИС ЖКХ.'; COMMENT ON COLUMN SPR_NSI.GROUP_NAME IS 'Название группы, если такая имеется, которая объединяет элементы справочника.'; COMMENT ON COLUMN SPR_NSI.CODE_PARENT IS 'Код родительского справочника.';"; SQL statement:
 COMMENT ON TABLE "PUBLIC".SPR_NSI IS 'Справочник НСИ ГИС ЖКХ.'COMMENT ON COLUMN SPR_NSI.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN SPR_NSI.NAME IS 'Наименование поля элемента справочника.'; COMMENT ON COLUMN SPR_NSI.CODE IS 'Код элемента справочника, уникальный в пределах справочника.'; COMMENT ON COLUMN SPR_NSI.GUID IS 'Глобально-уникальный идентификатор элемента справочника ГИС ЖКХ.'; COMMENT ON COLUMN SPR_NSI.GROUP_NAME IS 'Название группы, если такая имеется, которая объединяет элементы справочника.'; COMMENT ON COLUMN SPR_NSI.CODE_PARENT IS 'Код родительского справочника.'; [42000-190]
2016-06-26 14:58:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "'NSI' (SPR_NSI_TYPE: ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335 COMMENT STRINGDECODE('\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0430\u043f\u0438\u0441\u0435\u0439.'))"
Data conversion error converting "'NSI' (SPR_NSI_TYPE: ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335 COMMENT STRINGDECODE('\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0430\u043f\u0438\u0441\u0435\u0439.'))"; SQL statement:
INSERT INTO SPR_NSI_TYPE VALUES('NSI', 'NSIRAO') -- ('NSI', 'NSIRAO') [22018-190]
2016-06-26 14:58:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "'NSI' (SPR_NSI_TYPE: ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335 COMMENT STRINGDECODE('\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0430\u043f\u0438\u0441\u0435\u0439.'))"
Data conversion error converting "'NSI' (SPR_NSI_TYPE: ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335 COMMENT STRINGDECODE('\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0430\u043f\u0438\u0441\u0435\u0439.'))"; SQL statement:
INSERT INTO SPR_NSI_TYPE VALUES('NSI', 'NSIRAO') -- ('NSI', 'NSIRAO') [22018-190]
2016-06-26 14:58:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Ошибка преобразования данных при конвертации "'NSI' (SPR_NSI_TYPE: ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335 COMMENT STRINGDECODE('\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0430\u043f\u0438\u0441\u0435\u0439.'))"
Data conversion error converting "'NSI' (SPR_NSI_TYPE: ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_9A498524_83DA_45A1_8EF4_B73E2D033335 COMMENT STRINGDECODE('\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440 \u0437\u0430\u043f\u0438\u0441\u0435\u0439.'))"; SQL statement:
INSERT INTO SPR_NSI_TYPE VALUES('NSI', 'NSIRAO') -- ('NSI', 'NSIRAO') [22018-190]
2016-06-26 15:04:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE" не найден
Column "SPR_NSI_TYPE" not found; SQL statement:
INSERT INTO SPR_NSI_TYPE(SPR_NSI_TYPE) VALUES('NSI') [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:660)
	at org.h2.command.Parser.parseColumn(Parser.java:855)
	at org.h2.command.Parser.parseColumnList(Parser.java:839)
	at org.h2.command.Parser.parseInsert(Parser.java:1039)
	at org.h2.command.Parser.parsePrepared(Parser.java:400)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 21:53:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "DROP TABLE ""PUBLIC"".SPR_NSI95
DROP[*] TABLE ""PUBLIC"".SPR_NSI_TYPE"
Syntax error in SQL statement "DROP TABLE ""PUBLIC"".SPR_NSI95
DROP[*] TABLE ""PUBLIC"".SPR_NSI_TYPE"; SQL statement:
DROP TABLE "PUBLIC".SPR_NSI95
DROP TABLE "PUBLIC".SPR_NSI_TYPE [42000-190]
2016-06-26 23:34:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Данная функция не поддерживается: "getFunctions"
Feature not supported: "getFunctions" [50100-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:375)
	at org.h2.jdbc.JdbcDatabaseMetaData.getFunctions(JdbcDatabaseMetaData.java:3126)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getFunctions(JDBCDatabaseMetaDataImpl.java:231)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadProcedures(GenericMetaModel.java:180)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.loadProcedures(GenericObjectContainer.java:354)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPackages(GenericObjectContainer.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:697)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:427)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:353)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:184)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:34:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Данная функция не поддерживается: "getFunctions"
Feature not supported: "getFunctions" [50100-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:375)
	at org.h2.jdbc.JdbcDatabaseMetaData.getFunctions(JdbcDatabaseMetaData.java:3126)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getFunctions(JDBCDatabaseMetaDataImpl.java:231)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadProcedures(GenericMetaModel.java:180)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.loadProcedures(GenericObjectContainer.java:354)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getProcedures(GenericObjectContainer.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:697)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:427)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:353)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:184)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:39:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE.ID" не найден
Column "SPR_NSI_TYPE.ID" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD where NSI_TYPE = SPR_NSI_TYPE.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:39:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE.ID" не найден
Column "SPR_NSI_TYPE.ID" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD where NSI_FOR_DOWNLOAD.ID = SPR_NSI_TYPE.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:40:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE.NSI_TYPE" не найден
Column "SPR_NSI_TYPE.NSI_TYPE" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD where NSI_TYPE = SPR_NSI_TYPE.NSI_TYPE
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:41:13 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE.NSI_TYPE" не найден
Column "SPR_NSI_TYPE.NSI_TYPE" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD where NSI_TYPE = SPR_NSI_TYPE.NSI_TYPE
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:42:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE.NSI_TYPE" не найден
Column "SPR_NSI_TYPE.NSI_TYPE" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD where NSI_TYPE = SPR_NSI_TYPE.NSI_TYPE
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:45:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SELECTSPR_NSI_TYPE.ID" не найден
Column "SELECTSPR_NSI_TYPE.ID" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD where ID = selectSPR_NSI_TYPE.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:46:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE.ID" не найден
Column "SPR_NSI_TYPE.ID" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD  where ID = SPR_NSI_TYPE.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:48:05 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неоднозначное имя столбца "ID"
Ambiguous column name "ID"; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT ID, CODE, WORD_FOR_EXTRACT, NSI_TYPE FROM NSI_FOR_DOWNLOAD, SPR_NSI_TYPE  where SPR_NSI_TYPE.ID = NSI_FOR_DOWNLOAD.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [90059-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:124)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:94)
	at org.h2.command.dml.Select.mapColumns(Select.java:1185)
	at org.h2.command.dml.Select.init(Select.java:810)
	at org.h2.command.Parser.parseSelect(Parser.java:1682)
	at org.h2.command.Parser.parsePrepared(Parser.java:432)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:48:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неоднозначное имя столбца "ID"
Ambiguous column name "ID"; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT ID, CODE, WORD_FOR_EXTRACT, NSI_TYPE FROM NSI_FOR_DOWNLOAD, SPR_NSI_TYPE  where SPR_NSI_TYPE.ID = NSI_FOR_DOWNLOAD.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [90059-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:124)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:94)
	at org.h2.command.dml.Select.mapColumns(Select.java:1185)
	at org.h2.command.dml.Select.init(Select.java:810)
	at org.h2.command.Parser.parseSelect(Parser.java:1682)
	at org.h2.command.Parser.parsePrepared(Parser.java:432)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:48:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неоднозначное имя столбца "NSI_TYPE"
Ambiguous column name "NSI_TYPE"; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT NSI_FOR_DOWNLOAD.ID, CODE, WORD_FOR_EXTRACT, NSI_TYPE FROM NSI_FOR_DOWNLOAD, SPR_NSI_TYPE  where SPR_NSI_TYPE.ID = NSI_FOR_DOWNLOAD.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [90059-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.mapColumn(ExpressionColumn.java:124)
	at org.h2.expression.ExpressionColumn.mapColumns(ExpressionColumn.java:94)
	at org.h2.command.dml.Select.mapColumns(Select.java:1185)
	at org.h2.command.dml.Select.init(Select.java:810)
	at org.h2.command.Parser.parseSelect(Parser.java:1682)
	at org.h2.command.Parser.parsePrepared(Parser.java:432)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-26 23:54:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "SPR_NSI_TYPE.ID" не найден
Column "SPR_NSI_TYPE.ID" not found; SQL statement:
--DROP TABLE "PUBLIC".SPR_NSI95;
--DROP TABLE "PUBLIC".SPR_NSI_TYPE;
--DROP TABLE "PUBLIC".NSI_FOR_DOWNLOAD;
--CALL GET_MESSAGE();
SELECT * FROM NSI_FOR_DOWNLOAD  where NSI_FOR_DOWNLOAD.NSI_TYPE = SPR_NSI_TYPE.ID
--select * from GET_MESSAGE()
--select ID from OBMEN_OPERATION
/*CREATE ALIAS NEXT_PRIME AS $$
String nextPrime(String value) {
    return new BigInteger(value).nextProbablePrime().toString();
}
$$;*/ [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:180)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-27 10:53:34 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-27 11:42:10 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:79)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource(GenericMetaModel.java:86)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:149)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:593)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:71)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:551)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:123)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:182)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 40 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 35 more
2016-06-27 11:42:51 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:79)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource(GenericMetaModel.java:86)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:149)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:593)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:71)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:551)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:123)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:182)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 40 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 35 more
2016-06-27 14:38:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "COMMENT ON TABLE[*] \""PUBLIC\"".NSI_DATA_PROVIDER_FOR_DOWNLOAD IS 'Справочники для загрузки в БД ГРАД.';
COMMENT ON COLUMN NSI_DATA_PROVIDER_FOR_DOWNLOAD.ID IS 'Идентификатор записей.'"
Syntax error in SQL statement "COMMENT ON TABLE[*] \""PUBLIC\"".NSI_DATA_PROVIDER_FOR_DOWNLOAD IS 'Справочники для загрузки в БД ГРАД.';
COMMENT ON COLUMN NSI_DATA_PROVIDER_FOR_DOWNLOAD.ID IS 'Идентификатор записей.'"; SQL statement:
COMMENT ON TABLE \"PUBLIC\".NSI_DATA_PROVIDER_FOR_DOWNLOAD IS 'Справочники для загрузки в БД ГРАД.';
COMMENT ON COLUMN NSI_DATA_PROVIDER_FOR_DOWNLOAD.ID IS 'Идентификатор записей.' [42000-190]
2016-06-27 14:45:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "COMMENT ON TABLE[*] \""PUBLIC\"".NSI_DATA_PROVIDER_FOR_EXTRACT IS 'Таблица содержит перечень данных для извлечения нужных данных из справочников ГИС ЖКХ в БД ГРАД.';
COMMENT ON COLUMN NSI_DATA_PROVIDER_FOR_EXTRACT.ID IS 'Идентификатор записей.'"
Syntax error in SQL statement "COMMENT ON TABLE[*] \""PUBLIC\"".NSI_DATA_PROVIDER_FOR_EXTRACT IS 'Таблица содержит перечень данных для извлечения нужных данных из справочников ГИС ЖКХ в БД ГРАД.';
COMMENT ON COLUMN NSI_DATA_PROVIDER_FOR_EXTRACT.ID IS 'Идентификатор записей.'"; SQL statement:
COMMENT ON TABLE \"PUBLIC\".NSI_DATA_PROVIDER_FOR_EXTRACT IS 'Таблица содержит перечень данных для извлечения нужных данных из справочников ГИС ЖКХ в БД ГРАД.';
COMMENT ON COLUMN NSI_DATA_PROVIDER_FOR_EXTRACT.ID IS 'Идентификатор записей.' [42000-190]
2016-06-27 15:03:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "NSI_DATA_PROVIDER_FOR_DOWNLOAD[*]"
Syntax error in SQL statement "NSI_DATA_PROVIDER_FOR_DOWNLOAD[*]"; SQL statement:
NSI_DATA_PROVIDER_FOR_DOWNLOAD [42000-190]
2016-06-27 15:03:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "WORD_FOR_EXTRACT" не найден
Column "WORD_FOR_EXTRACT" not found; SQL statement:
INSERT INTO NSI_DATA_PROVIDER_FOR_DOWNLOAD(CODE, WORD_FOR_EXTRACT) VALUES('1', 'Вид дополнительной услуги') [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:660)
	at org.h2.command.Parser.parseColumn(Parser.java:855)
	at org.h2.command.Parser.parseColumnList(Parser.java:839)
	at org.h2.command.Parser.parseInsert(Parser.java:1039)
	at org.h2.command.Parser.parsePrepared(Parser.java:400)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:177)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-27 15:05:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "WORD_FOR_EXTRACT" не найден
Column "WORD_FOR_EXTRACT" not found; SQL statement:
INSERT INTO NSI_DATA_PROVIDER_FOR_DOWNLOAD(CODE, WORD_FOR_EXTRACT) VALUES('1', 'Вид дополнительной услуги') [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:660)
	at org.h2.command.Parser.parseColumn(Parser.java:855)
	at org.h2.command.Parser.parseColumnList(Parser.java:839)
	at org.h2.command.Parser.parseInsert(Parser.java:1039)
	at org.h2.command.Parser.parsePrepared(Parser.java:400)
	at org.h2.command.Parser.parse(Parser.java:304)
	at org.h2.command.Parser.parse(Parser.java:276)
	at org.h2.command.Parser.prepareCommand(Parser.java:241)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.run(SQLQueryJob.java:177)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-28 10:57:03 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-28 10:57:13 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setRequest(SaveToBaseMessages.java:35)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:102)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportOrgRegistry.callExportOrgRegistry(ExportOrgRegistry.java:66)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:59)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-28 10:57:13 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setResult(SaveToBaseMessages.java:69)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:104)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportOrgRegistry.callExportOrgRegistry(ExportOrgRegistry.java:66)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:59)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-28 10:57:14 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setRequest(SaveToBaseMessages.java:35)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:102)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportDataProvider.callExportDataProvide(ExportDataProvider.java:56)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:63)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-28 10:57:14 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setMessageToBase(SaveToBaseMessages.java:124)
	at ru.progmatik.java.pregis.connectiondb.SaveToBaseMessages.setResult(SaveToBaseMessages.java:69)
	at ru.progmatik.java.pregis.other.AnswerProcessing.sendToBaseAndAnotherError(AnswerProcessing.java:104)
	at ru.progmatik.java.pregis.services.organizations.common.service.ExportDataProvider.callExportDataProvide(ExportDataProvider.java:56)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:63)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-28 10:57:14 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.SaveToBaseOrganization.setOrganization(SaveToBaseOrganization.java:34)
	at ru.progmatik.java.pregis.ProgramAction.getSenderID(ProgramAction.java:68)
	at ru.progmatik.java.pregis.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-28 10:57:14 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.UsersDAO.<init>(UsersDAO.java:24)
	at ru.progmatik.java.web.accounts.ProfileSingleton.<init>(ProfileSingleton.java:27)
	at ru.progmatik.java.web.accounts.ProfileSingleton.instance(ProfileSingleton.java:46)
	at ru.progmatik.java.web.servlets.web.LoginClient.<init>(LoginClient.java:45)
	at ru.progmatik.java.web.servlets.web.LoginClient.<init>(LoginClient.java:49)
	at ru.progmatik.java.pregis.Main.main(Main.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 38 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 33 more
2016-06-28 11:05:33 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-28 12:53:51 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-06-29 00:06:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "SELECT ABONLS FROM ACCOUNT_FOR_REMOVE WHERE ABONLS = '123'
DROP[*] TABLE ""PUBLIC"".ACCOUNT_FOR_REMOVE"
Syntax error in SQL statement "SELECT ABONLS FROM ACCOUNT_FOR_REMOVE WHERE ABONLS = '123'
DROP[*] TABLE ""PUBLIC"".ACCOUNT_FOR_REMOVE"; SQL statement:
SELECT ABONLS FROM ACCOUNT_FOR_REMOVE WHERE ABONLS = '123'
DROP TABLE "PUBLIC".ACCOUNT_FOR_REMOVE [42000-192]
2016-06-29 00:07:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID IDENTITY NOT NULL PRIMARY KEY,
         					ABONID BIGINT NOT NULL,
         					ABONLS VARCHAR(255) NOT NULL,
            				FIO VARCHAR(255) NOT NULL,
            				ENDDATE DATE,
            				NSICODE VARCHAR(20)
            				CLOSED[*] BOOLEAN(FALSE)) "; ожидалось "FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID IDENTITY NOT NULL PRIMARY KEY,
         					ABONID BIGINT NOT NULL,
         					ABONLS VARCHAR(255) NOT NULL,
            				FIO VARCHAR(255) NOT NULL,
            				ENDDATE DATE,
            				NSICODE VARCHAR(20)
            				CLOSED[*] BOOLEAN(FALSE)) "; expected "FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID identity not null primary key,
         					ABONID bigint not null,
         					ABONLS varchar(255) not null,
            				FIO varchar(255) not null,
            				ENDDATE date,
            				NSICODE varchar(20)
            				CLOSED boolean(false)) [42001-192]
2016-06-29 00:07:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID IDENTITY NOT NULL PRIMARY KEY,
         					ABONID BIGINT NOT NULL,
         					ABONLS VARCHAR(255) NOT NULL,
            				FIO VARCHAR(255) NOT NULL,
            				ENDDATE DATE,
            				NSICODE VARCHAR(20)
            				CLOSED[*] BOOLEAN(FALSE) NOT NULL) "; ожидалось "FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID IDENTITY NOT NULL PRIMARY KEY,
         					ABONID BIGINT NOT NULL,
         					ABONLS VARCHAR(255) NOT NULL,
            				FIO VARCHAR(255) NOT NULL,
            				ENDDATE DATE,
            				NSICODE VARCHAR(20)
            				CLOSED[*] BOOLEAN(FALSE) NOT NULL) "; expected "FOR, UNSIGNED, NOT, NULL, AS, DEFAULT, GENERATED, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID identity not null primary key,
         					ABONID bigint not null,
         					ABONLS varchar(255) not null,
            				FIO varchar(255) not null,
            				ENDDATE date,
            				NSICODE varchar(20)
            				CLOSED boolean(false) not null) [42001-192]
2016-06-29 00:07:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID IDENTITY NOT NULL PRIMARY KEY,
         					ABONID BIGINT NOT NULL,
         					ABONLS VARCHAR(255) NOT NULL,
            				FIO VARCHAR(255) NOT NULL,
            				ENDDATE DATE,
            				NSICODE VARCHAR(20),
            				CLOSED BOOLEAN(FALSE[*]) NOT NULL) "; ожидалось "integer"
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID IDENTITY NOT NULL PRIMARY KEY,
         					ABONID BIGINT NOT NULL,
         					ABONLS VARCHAR(255) NOT NULL,
            				FIO VARCHAR(255) NOT NULL,
            				ENDDATE DATE,
            				NSICODE VARCHAR(20),
            				CLOSED BOOLEAN(FALSE[*]) NOT NULL) "; expected "integer"; SQL statement:
CREATE TABLE IF NOT EXISTS ACCOUNT_FOR_REMOVE (
         					ID identity not null primary key,
         					ABONID bigint not null,
         					ABONLS varchar(255) not null,
            				FIO varchar(255) not null,
            				ENDDATE date,
            				NSICODE varchar(20),
            				CLOSED boolean(false) not null) [42001-192]
2016-06-29 00:10:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO ACCOUNT_FOR_REMOVE VALUES(DEFAULT, '123', '156', 'FIO') [21002-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:265)
	at org.h2.command.Parser.prepareCommand(Parser.java:259)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1202)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:342)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:719)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1494)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-29 00:13:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "CLOSET" не найден
Column "CLOSET" not found; SQL statement:
SELECT ABONLS FROM ACCOUNT_FOR_REMOVE WHERE CLOSET = false [42122-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Select.prepare(Select.java:855)
	at org.h2.command.Parser.prepareCommand(Parser.java:259)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1202)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:342)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:719)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1494)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-29 00:14:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO ACCOUNT_FOR_REMOVE(ABONID, ABONLS, FIO, CLOSED) VALUES(123, '156', 'FIO' FALSE[*])"; ожидалось "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"
Syntax error in SQL statement "INSERT INTO ACCOUNT_FOR_REMOVE(ABONID, ABONLS, FIO, CLOSED) VALUES(123, '156', 'FIO' FALSE[*])"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO ACCOUNT_FOR_REMOVE(ABONID, ABONLS, FIO, CLOSED) VALUES(123, '156', 'FIO' FALSE) [42001-192]
2016-06-30 19:18:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Данная функция не поддерживается: "getFunctions"
Feature not supported: "getFunctions" [50100-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:375)
	at org.h2.jdbc.JdbcDatabaseMetaData.getFunctions(JdbcDatabaseMetaData.java:3130)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getFunctions(JDBCDatabaseMetaDataImpl.java:231)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadProcedures(GenericMetaModel.java:179)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.loadProcedures(GenericObjectContainer.java:354)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getPackages(GenericObjectContainer.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:719)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:449)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:375)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:192)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-06-30 19:18:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Данная функция не поддерживается: "getFunctions"
Feature not supported: "getFunctions" [50100-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:216)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:375)
	at org.h2.jdbc.JdbcDatabaseMetaData.getFunctions(JdbcDatabaseMetaData.java:3130)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCDatabaseMetaDataImpl.getFunctions(JDBCDatabaseMetaDataImpl.java:231)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.loadProcedures(GenericMetaModel.java:179)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.loadProcedures(GenericObjectContainer.java:354)
	at org.jkiss.dbeaver.ext.generic.model.GenericObjectContainer.getProcedures(GenericObjectContainer.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.extractPropertyValue(DBNDatabaseNode.java:719)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadTreeItems(DBNDatabaseNode.java:449)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.loadChildren(DBNDatabaseNode.java:375)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:192)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-07-01 03:13:06 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-07-01 03:18:31 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:190)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:353)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:385)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:227)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at ru.progmatik.java.pregis.connectiondb.ConnectionDB.getConnectionDB(ConnectionDB.java:58)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.<init>(BaseOrganization.java:27)
	at ru.progmatik.java.pregis.connectiondb.localdb.organization.BaseOrganization.getSenderID(BaseOrganization.java:53)
	at ru.progmatik.java.pregis.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 35 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 30 more
2016-07-01 16:00:11 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE IF NOT EXISTS METERING_DEVICE_IDENTIFIERS (ID IDENTITY NOT NULL PRIMARY KEY, ABON_ID INT NOT NULL, HOUSE_ID INT NOT NULL, ACCOUNT_GUID VARCHAR(40), PREMISE_GUID VARCHAR(40), LIVING_ROOM_GUID VARCHAR(40), METERING_DEVICE_NUMBER VARCHAR(255), METERING_UNIQUE_NUMBER VARCHAR(40), METERING_ROOT_GUID VARCHAR(40), METERING_VERSION_GUID VARCHAR(40), TRANSPORT_GUID VARCHAR(40)),[*] NON_RESIDENTIAL_PREMISE_DEVICE BOOLEAN NOT NULL); COMMENT ON TABLE ""PUBLIC"".METERING_DEVICE_IDENTIFIERS IS 'Таблица содержит идентификаторы приборов учёта, полученых из ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ABON_ID IS 'ИД абонента в БД ГРАД.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.HOUSE_ID IS 'ИД дома в БД ГРАД.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ACCOUNT_GUID IS 'Идентификатор ЛС в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.PREMISE_GUID IS 'Идентификатор жилого помещения в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.LIVING_ROOM_GUID IS 'Идентификатор комнаты в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_DEVICE_NUMBER IS 'Номер ПУ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_UNIQUE_NUMBER IS 'Уникальный реестровый номер в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_ROOT_GUID IS 'Идентификатор ПУ в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_VERSION_GUID IS 'Идентификатор версии ПУ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.TRANSPORT_GUID IS 'Транспортный идентификатор.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.NON_RESIDENTIAL_PREMISE_DEVICE IS 'Указать true если помещение нежилое.'; "
Syntax error in SQL statement "CREATE TABLE IF NOT EXISTS METERING_DEVICE_IDENTIFIERS (ID IDENTITY NOT NULL PRIMARY KEY, ABON_ID INT NOT NULL, HOUSE_ID INT NOT NULL, ACCOUNT_GUID VARCHAR(40), PREMISE_GUID VARCHAR(40), LIVING_ROOM_GUID VARCHAR(40), METERING_DEVICE_NUMBER VARCHAR(255), METERING_UNIQUE_NUMBER VARCHAR(40), METERING_ROOT_GUID VARCHAR(40), METERING_VERSION_GUID VARCHAR(40), TRANSPORT_GUID VARCHAR(40)),[*] NON_RESIDENTIAL_PREMISE_DEVICE BOOLEAN NOT NULL); COMMENT ON TABLE ""PUBLIC"".METERING_DEVICE_IDENTIFIERS IS 'Таблица содержит идентификаторы приборов учёта, полученых из ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ABON_ID IS 'ИД абонента в БД ГРАД.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.HOUSE_ID IS 'ИД дома в БД ГРАД.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ACCOUNT_GUID IS 'Идентификатор ЛС в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.PREMISE_GUID IS 'Идентификатор жилого помещения в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.LIVING_ROOM_GUID IS 'Идентификатор комнаты в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_DEVICE_NUMBER IS 'Номер ПУ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_UNIQUE_NUMBER IS 'Уникальный реестровый номер в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_ROOT_GUID IS 'Идентификатор ПУ в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_VERSION_GUID IS 'Идентификатор версии ПУ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.TRANSPORT_GUID IS 'Транспортный идентификатор.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.NON_RESIDENTIAL_PREMISE_DEVICE IS 'Указать true если помещение нежилое.'; "; SQL statement:
CREATE TABLE IF NOT EXISTS METERING_DEVICE_IDENTIFIERS (ID identity not null primary key, ABON_ID INT not null, HOUSE_ID INT not null, ACCOUNT_GUID varchar(40), PREMISE_GUID varchar(40), LIVING_ROOM_GUID varchar(40), METERING_DEVICE_NUMBER varchar(255), METERING_UNIQUE_NUMBER varchar(40), METERING_ROOT_GUID varchar(40), METERING_VERSION_GUID varchar(40), TRANSPORT_GUID varchar(40)), NON_RESIDENTIAL_PREMISE_DEVICE boolean not null); COMMENT ON TABLE "PUBLIC".METERING_DEVICE_IDENTIFIERS IS 'Таблица содержит идентификаторы приборов учёта, полученых из ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ID IS 'Идентификатор записей.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ABON_ID IS 'ИД абонента в БД ГРАД.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.HOUSE_ID IS 'ИД дома в БД ГРАД.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.ACCOUNT_GUID IS 'Идентификатор ЛС в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.PREMISE_GUID IS 'Идентификатор жилого помещения в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.LIVING_ROOM_GUID IS 'Идентификатор комнаты в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_DEVICE_NUMBER IS 'Номер ПУ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_UNIQUE_NUMBER IS 'Уникальный реестровый номер в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_ROOT_GUID IS 'Идентификатор ПУ в ГИС ЖКХ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.METERING_VERSION_GUID IS 'Идентификатор версии ПУ.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.TRANSPORT_GUID IS 'Транспортный идентификатор.'; COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.NON_RESIDENTIAL_PREMISE_DEVICE IS 'Указать true если помещение нежилое.'; [42000-190]
2016-07-01 16:01:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "METERING_DEVICE_IDENTIFIERS" не найдена
Table "METERING_DEVICE_IDENTIFIERS" not found; SQL statement:
COMMENT ON COLUMN METERING_DEVICE_IDENTIFIERS.NON_RESIDENTIAL_PREMISE_DEVICE IS 'Указать true если помещение нежилое.' [42102-190]
2016-07-01 16:20:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "DSF" не найден
Column "DSF" not found; SQL statement:
INSERT INTO METERING_DEVICE_IDENTIFIERS VALUES(DEFAULT, 111, 222, dsf, gfdsgsdf, dfregr, fdsfdsfdsf, fdsfds, Hello, dsf, World, false) [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-07-01 16:21:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Столбец "DSF" не найден
Column "DSF" not found; SQL statement:
INSERT INTO METERING_DEVICE_IDENTIFIERS VALUES(DEFAULT, 111, 222, dsf, gfdsgsdf, dfregr, fdsfdsfdsf, fdsfds, Hello, dsf, World, false) [42122-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.command.dml.Insert.prepare(Insert.java:270)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:460)
	at org.h2.engine.Session.prepareCommand(Session.java:402)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:170)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:345)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:138)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:328)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:686)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:1400)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:137)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
2016-07-01 17:13:14 database: flush
org.h2.message.DbException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:94)
	at org.h2.mvstore.MVStore.panic(MVStore.java:373)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:356)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2888)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)
	at org.h2.engine.Database.getPageStore(Database.java:2450)
	at org.h2.engine.Database.open(Database.java:672)
	at org.h2.engine.Database.openDatabase(Database.java:269)
	at org.h2.engine.Database.<init>(Database.java:263)
	at org.h2.engine.Engine.openSession(Engine.java:65)
	at org.h2.engine.Engine.openSession(Engine.java:175)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:153)
	at org.h2.engine.Engine.createSession(Engine.java:136)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
	at org.h2.Driver.connect(Driver.java:72)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:158)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:73)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.<init>(JDBCDataSource.java:94)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:79)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSource(GenericMetaModel.java:86)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:149)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:593)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:71)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:101)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:129)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.initConnection(DataSourceDescriptor.java:551)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:123)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:182)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:57)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:82)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:69)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.h2.jdbc.JdbcSQLException: Внутренняя ошибка: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]" [50000-190]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 40 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/andryha/project/workspace_for_git/PreGIS/db/pregisdb.h2.db.mv.db [1.4.190/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.FileStore.open(FileStore.java:172)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:342)
	... 35 more
